-- liquibase formatted sql

-- changeSet firiv:1

CREATE TABLE notification_task
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id BIGINT                                  NOT NULL,
    text    VARCHAR(255),
    time    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_notificationtask PRIMARY KEY (id)
);

-- changeSet firiv:2

ALTER TABLE notification_task
    ADD CONSTRAINT chat_id_text_time_unique UNIQUE (chat_id, text, time);

-- changeSet firiv:3

ALTER TABLE notification_task
    DROP CONSTRAINT chat_id_text_time_unique